// Kept exclusively on the server: the browser never downloads the answer deck.
export const SIP_WORDS = [
  {
    category: "Café favourites",
    words: [
      "Filter coffee|kaapi|coffee",
      "Masala dosa|dosa",
      "Idli|idly",
      "Medu vada|vada|vadai",
      "Sambar|sambhar",
      "Coconut chutney|chutney",
      "Pongal",
      "Upma",
      "Bajji|bhaji",
      "Samosa",
      "Lemon rice",
      "Curd rice",
      "Biryani|biriyani",
      "Parotta|paratha",
      "Tea|chai",
      "Lassi",
      "Rose milk",
      "Sugar",
      "Banana leaf",
      "Steel tumbler|tumbler",
      "Lunch box|lunchbox",
      "Pickle",
      "Ice cream|icecream",
      "Gulab jamun",
    ],
  },
  {
    category: "Weekend plans",
    words: [
      "Beach",
      "Cinema|movie theater|movie theatre",
      "Cricket",
      "Picnic",
      "Road trip",
      "Shopping",
      "Camping",
      "Dancing|dance",
      "Karaoke",
      "Swimming|swim",
      "Train journey|train",
      "Birthday party|birthday",
    ],
  },
  {
    category: "Everyday things",
    words: [
      "Umbrella",
      "Headphones|earphones",
      "Bicycle|cycle|bike",
      "Backpack|bag",
      "Sunglasses",
      "Alarm clock|alarm",
      "Auto rickshaw|auto|rickshaw",
      "Ceiling fan|fan",
      "Newspaper",
      "Remote control|remote",
      "Selfie",
      "Rain|rainfall",
    ],
  },
].flatMap(({ category, words }) => words.map((entry) => ({ category, aliases: entry.split("|") })));

export const normalizeSipWord = (word: string): string =>
  word.toLowerCase().replace(/[^a-z0-9]/g, "");
